### ISSUE TITLE
Touchdown Checklist

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/HearSee#1]
- [x] Play audio once the options are configured on first page
- [x] color map thingy
- [x] Add page for customizing the closest distance node
- [x] Finish writing all the mark ups
- [x] Do a cover image
- [x] Write the essays
- [x] Update resume for Apple

## If Have Time?

> I don't think I have time though

- [ ] Add cut scene
